export const NavigationRoutes = {
  AuthLoading: 'AuthLoading',
  Home: 'Home',
  Welcome: 'Welcome',
  UserInfo: 'UserInfo',
  IdealFigure: 'KJ calculator',
  BurnkJ: 'Burn kJ',
  Profile: 'Profile',
  Search: 'Search',
  SearchForm: 'SearchForm',
  Meal: 'Meal',
  More: 'More',
  Converter: 'Converter',
  LegalStuff: 'LegalStuff',
  LegalStuffMore: 'LegalStuffMore',
  YourIdealFigure: 'YourIdealFigure',
  WeightGoal: 'WeightGoal',
  WhichOutlets: 'WhichOutlets',
  AboutkJs: 'AboutkJs',
  KilojoulesAndKids: 'KilojoulesAndKids',
  AboutTheCampaign: 'AboutTheCampaign',
};
